spring.application.name=asr-java
server.port=17008
server.servlet.context-path=/asr
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

asr.model-dir=resource/asr/model/asr-model
asr.punctuation-model-dir=resource/asr/model/punctuation-model
asr.config-dir=resource/asr/config
asr.upload-dir=resource/asr/uploads
asr.hotwords-dir=resource/asr/runtime/hotwords
asr.runtime-java-jar=auto
asr.runtime-native-jar=auto
asr.runtime-provider=cpu
asr.num-threads=2
asr.hotwords-score=1.5
asr.decoding-method=modified_beam_search
asr.streaming-model=true
