---
baseTerms:
- "点位"
- "周界点位"
- "监控"
- "监控点"
- "预览"
- "回放"
- "摄像头"
- "电视墙"
- "上墙"
- "分屏"
- "云台"
- "预置位"
- "巡航"
- "报警"
- "门禁"
- "监门"
- "干警通道"
- "车行通道"
- "周界"
- "监墙"
- "伙房"
- "会见楼"
- "监区"
- "严管监区"
- "监区车间"
- "狱内管控中心"
- "监舍"
- "固定包房"
- "宣传室"
- "后整理车间"
- "总装车间"
- "下料车间"
- "管件车间"
- "缝纫车间"
- "机加工车间"
- "机加工北车间"
- "筒壳南车间"
- "筒壳北车间"
- "筒壳车间"
- "筒壳北外协办材料库"
- "冲压车间"
- "冲压外协办缝纫机库"
- "外协办成品库"
- "西监区域"
- "生产区域"
- "脱逃"
- "袭警"
- "暴狱"
- "哄监闹事"
- "哄监闹狱"
- "行凶"
- "群殴"
- "持械"
- "狱外人员"
- "冲击监狱"
- "离监就医"
- "震灾"
- "值班主任"
- "总值班长"
- "驻监武警部队"
- "各押犯单位"
- "押犯单位"
- "改造副监狱长"
- "科长"
- "狱政科"
- "狱政科长"
- "狱政管理科"
- "狱侦科长"
- "狱侦科"
- "狱内侦察科"
- "教育科长"
- "教育科"
- "教育改造科"
- "刑罚科科长"
- "刑罚科长"
- "刑罚科"
- "刑罚执行科"
- "各监区监区长"
- "追逃"
- "联勤联值单元"
- "和衣班警察"
- "备勤警察"
- "管控中心"
- "整理车间"
- "加工车间"
- "南车间"
- "北车间"
- "外协办"
- "材料库"
- "缝纫机库"
- "成品库"
- "闹事"
- "闹狱"
- "离监"
- "武警部队"
- "副监狱长"
- "监狱长"
- "管理科"
- "侦察科"
- "改造科"
- "执行科"
- "监区长"
- "联勤联值"
- "联值单元"
- "警察"
- "和衣班"
- "备勤"
- "监所内"
- "一监区"
- "二监区"
- "三监区"
- "四监区"
- "五监区"
- "六监区"
- "七监区"
- "八监区"
- "九监区"
- "十监区"
- "第一监区"
- "第二监区"
- "第三监区"
- "第四监区"
- "第五监区"
- "第六监区"
- "第七监区"
- "第八监区"
- "第九监区"
- "第十监区"
